'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalized=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let records=[],registry,current,limit=12,trigger,toastTimer;
const unknown='Não verificado nesta edição';
const allowedURL=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:null}catch{return null}};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Texto copiado. Revise os campos antes de utilizar.')}catch{toast('A cópia foi bloqueada pelo navegador. Selecione o texto no guia e copie manualmente.')}}
function download(filename,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function theme(value){document.documentElement.dataset.theme=value;$('theme').setAttribute('aria-label',value==='dark'?'Ativar modo claro':'Ativar modo escuro');$('theme').textContent=value==='dark'?'☼':'☾';try{localStorage.setItem('costal-agents-theme',value)}catch{}}
let saved;try{saved=localStorage.getItem('costal-agents-theme')}catch{}theme(saved==='light'?'light':'dark');
$('theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
function movement(){document.documentElement.classList.toggle('paused',paused);$('motion').textContent=paused?'▶':'Ⅱ';$('motion').setAttribute('aria-pressed',String(paused));$('motion').setAttribute('aria-label',paused?'Ativar animação':'Pausar animação')}
$('motion').onclick=()=>{paused=!paused;movement()};movement();
const helpPrompt='Estou consultando a página independente Agentes de IA COSTAL: https://ai-robots-galeria.netlify.app/agentes/ . O catálogo, as fichas técnicas e os guias estão nesse endereço. Ajude-me em português a compreender as funções e os guias. Confira as fontes; se não conseguir acessá-las, peça o trecho necessário. Não presuma que um agente está disponível ou que possui integrações não verificadas. Diferencie descrição da galeria, orientação preliminar e capacidade comprovada. Pergunte qual agente ou tarefa quero entender.';
$('chatgpt').href='https://chatgpt.com/?q='+encodeURIComponent(helpPrompt);$('claude').href='https://claude.ai/new?q='+encodeURIComponent(helpPrompt);
function available(a){return a.status==='Disponível'&&a.accessVerified===true&&allowedURL(a.accessUrl)}
async function load(){
 $('load-error').hidden=true;$('cards').innerHTML='<p class="load">Carregando catálogo…</p>';$('export').disabled=true;
 try{
  const [galleryResponse,registryResponse]=await Promise.all([fetch('../index.html',{cache:'no-cache'}),fetch('registro.json',{cache:'no-cache'})]);
  if(!galleryResponse.ok||!registryResponse.ok)throw Error('Fonte indisponível');
  const doc=new DOMParser().parseFromString(await galleryResponse.text(),'text/html');
  const data=doc.querySelector('#agent-data');if(!data)throw Error('Fonte não reconhecida');
  const gallery=JSON.parse(data.textContent);registry=await registryResponse.json();
  records=gallery.filter(a=>!a.spare).map(a=>({...a,id:'CST-AI-'+a.name.replaceAll(' ','-'),area:'A classificar',status:'A confirmar',...(registry.agents[a.name]||{}),image:new URL('../'+a.file.split('/').map(encodeURIComponent).join('/'),location.href).href}));
  records.push(...(registry.additionalAgents||[]));records.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
  $('metrics').innerHTML=[[records.length,'registros no catálogo'],[records.filter(a=>a.guide).length,'guias de uso'],[records.filter(available).length,'acessos validados']].map(([n,l])=>`<div class="metric"><strong>${n}</strong><span>${l}</span></div>`).join('');
  $('notice-text').textContent=registry.notice;
  for(const key of ['area','status']){const previous=$(key).value;$(key).innerHTML=`<option value="">${key==='area'?'Todas as áreas':'Todas as situações'}</option>`+[...new Set(records.map(a=>a[key]))].sort().map(v=>`<option>${esc(v)}</option>`).join('');$(key).value=previous;}
  $('pilot-links').innerHTML=records.filter(a=>a.guide).map(a=>`<button data-name="${esc(a.name)}">${esc(a.name)}</button>`).join('');
  $('pilot-links').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.name,'guide',b));
  $('export').disabled=false;render();
 }catch(error){$('cards').innerHTML='';$('results').textContent='Catálogo temporariamente indisponível.';$('load-error').hidden=false;$('more').hidden=true;console.error(error)}
}
function render(){const query=normalized($('search').value).trim();const filtered=records.filter(a=>(!query||normalized([a.name,a.edition,a.role,a.description,a.area,...(a.aliases||[])].join(' ')).includes(query))&&(!$('area').value||a.area===$('area').value)&&(!$('status').value||a.status===$('status').value)&&(!$('guide').value||a.guide));
 $('results').textContent=`${filtered.length} agente${filtered.length===1?'':'s'} encontrado${filtered.length===1?'':'s'} · exibindo ${Math.min(limit,filtered.length)}`;
 $('cards').innerHTML=filtered.slice(0,limit).map(a=>`<article class="card"><div class="card-top">${a.image?`<img class="portrait" src="${esc(a.image)}" alt="" loading="lazy" width="90" height="90">`:`<span class="portrait initials" aria-hidden="true">${esc(a.name.split(/\s+/).map(w=>w[0]).slice(0,2).join(''))}</span>`}<div><h3>${esc(a.name)}</h3><p class="role">${esc(a.role)}</p></div></div><div class="card-body"><span class="badge ${available(a)?'available':''}">${esc(a.status)}</span><p class="description">${esc(a.description)}</p><span class="area">${esc(a.area)}</span><div class="card-actions"><button data-name="${esc(a.name)}" data-panel="guide">${a.guide?'Como usar':'Conhecer escopo'}</button><button data-name="${esc(a.name)}" data-panel="tech">Ficha técnica</button>${available(a)?`<a class="primary" href="${esc(allowedURL(a.accessUrl))}" target="_blank" rel="noopener">Abrir agente ↗</a>`:''}</div><p class="access-note">${available(a)?'Acesso validado; respeita as permissões da plataforma.':a.implemented?'Configuração consultada; uso pela equipe pendente de validação.':'Acesso e implementação ainda não verificados.'}</p></div></article>`).join('')||'<p class="empty">Nenhum agente encontrado. Tente outro termo ou altere os filtros.</p>';
 $('cards').querySelectorAll('button[data-name]').forEach(b=>b.onclick=()=>openDetail(b.dataset.name,b.dataset.panel,b));$('more').hidden=filtered.length<=limit;
}
for(const id of ['search','area','status','guide'])$(id).addEventListener(id==='search'?'input':'change',()=>{limit=12;render()});$('more').onclick=()=>{limit+=12;render()};$('retry').onclick=load;
const list=(items,ordered=false)=>`<${ordered?'ol':'ul'}>${items.map(t=>`<li>${esc(t)}</li>`).join('')}</${ordered?'ol':'ul'}>`;
function techFields(a){return [['Identificador',a.id],['Função catalogada',a.role],['Área de referência',a.area],['Situação',a.status],['Responsável pelo conteúdo',a.owner||'A definir'],['Responsável técnico',a.technicalOwner||'A definir'],['Plataforma',a.platform||unknown],['Versão do agente',a.version||unknown],['Link de uso',a.accessUrl||'Não fornecido'],['Acesso pelo público',a.accessVerified?'Verificado':'Pendente de teste'],['Última revisão da implementação',a.reviewedAt||'Pendente'],['Documentação',a.documentationStatus||'Em elaboração'],['Fontes de conhecimento',a.knowledgeSummary||unknown],['Ferramentas e integrações',a.toolsSummary||unknown],['Autonomia e aprovações',a.autonomySummary||unknown],['Limites, custos e dependências',a.limitsSummary||unknown],['Origem do escopo',a.evidenceSource||'Galeria AI Robots · consulta em 07/10/2026']];}
function openDetail(name,panel,button){current=records.find(a=>a.name===name);if(!current)return;trigger=button;const a=current,g=a.guide;$('detail-id').textContent=a.id+' · '+a.status;$('detail-title').textContent=a.name;$('detail-role').textContent=a.role;
 $('guide-panel').innerHTML=g?`<p class="callout">${esc(g.basis||'Guia conceitual, baseado na função descrita na galeria. Validar na implementação antes de adotar como procedimento.')}</p><h3>Quando utilizar</h3><p>${esc(g.when)}</p><p><b>Público:</b> ${esc(g.audience)}</p><h3>O que preparar</h3>${list(g.inputs)}<h3>Passo a passo</h3>${list(g.steps,true)}<h3>Pedido de exemplo</h3><pre>${esc(g.prompt)}</pre><h3>Exemplo didático</h3><p><b>Entrada:</b> ${esc(g.exampleInput)}</p><p><b>Resultado esperado:</b> ${esc(g.exampleOutput)}</p><p class="muted">Caso fictício para treinamento. Não representa um teste executado no agente.</p><h3>Como conferir</h3>${list(g.review)}<h3>Limitações a considerar</h3><p>${esc(g.limits)}</p>`:`<h3>Escopo registrado na galeria</h3><p>${esc(a.description)}</p><p class="callout">O guia específico depende do levantamento da implementação. Esta ficha não confirma que o agente está disponível.</p><h3>Antes de utilizar</h3>${list(['Confirmar a plataforma e o link com o responsável.','Conferir fontes, ferramentas e permissões do agente.','Realizar um exemplo fictício e revisar o resultado.','Registrar limites e critérios de aprovação no guia específico.'])}`;
 $('tech-panel').innerHTML=`<h3>Ficha de inventário · ${esc(registry.revision)}</h3><p class="muted">${a.implemented?'Configuração consultada. Testes funcionais, custos e acesso pela equipe pendentes.':'Escopo importado da galeria; implementação ainda não conferida.'}</p><dl class="facts">${techFields(a).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><h3>Escopo de referência</h3><p>${esc(a.description)}</p><h3>Roteiro de validação proposto</h3>${list(g?g.tests:['Executar uma tarefa representativa do escopo com dados fictícios.','Omitir uma informação necessária e verificar se o agente sinaliza a lacuna.','Solicitar algo fora do escopo e verificar como o limite é comunicado.'])}<p class="callout">Testes ainda não executados nesta edição. Registrar resultado, evidência, data e revisor antes de mudar a situação para “Disponível”.</p><h3>Configuração e manutenção</h3><p>Usar o modelo de documentação para registrar instruções, arquivos de conhecimento, ferramentas, autorizações, versões e alterações em local autorizado. Não incluir segredos ou documentos restritos neste catálogo público.</p><a href="modelo-documentacao.md" download>Baixar modelo completo de documentação</a>`;
 $('copy-prompt').hidden=!g;switchPanel(panel);$('detail').showModal();document.body.classList.add('modal-open');$(panel==='tech'?'tab-tech':'tab-guide').focus();
}
function switchPanel(panel){for(const k of ['guide','tech']){const selected=k===panel;$('tab-'+k).setAttribute('aria-selected',String(selected));$('tab-'+k).tabIndex=selected?0:-1;$(k+'-panel').hidden=!selected;}}
for(const key of ['guide','tech']){$('tab-'+key).onclick=()=>switchPanel(key);$('tab-'+key).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'guide':e.key==='End'?'tech':key==='guide'?'tech':'guide';switchPanel(next);$('tab-'+next).focus()}}}
$('close').onclick=()=>$('detail').close();$('detail').addEventListener('close',()=>{document.body.classList.remove('modal-open');trigger?.focus()});$('copy-prompt').onclick=()=>current?.guide&&copy(current.guide.prompt);$('copy-base').onclick=()=>copy($('base-prompt').textContent);
function markdown(a){let s=`# ${a.name} — ${a.role}\n\nEdição documental: ${registry.revision} · ${registry.date}\n\n${registry.notice}\n\n## Ficha técnica de inventário\n\n`+techFields(a).map(([k,v])=>`- ${k}: ${v}`).join('\n')+`\n\n## Escopo registrado\n\n${a.description}\n\n`;if(a.guide){const g=a.guide;s+='## Guia de uso\n\n'+(g.basis||'Orientação conceitual baseada na galeria.')+'\n\n'+g.when+'\n\nPúblico: '+g.audience+'\n\n';for(const [title,items] of [['Preparação',g.inputs],['Passo a passo',g.steps],['Conferência',g.review],['Testes propostos, ainda não executados',g.tests]])s+=`### ${title}\n\n`+items.map((t,i)=>`${i+1}. ${t}`).join('\n')+'\n\n';s+=`### Pedido de exemplo\n\n${g.prompt}\n\n### Caso fictício\n\n${g.exampleInput}\n\nResultado esperado: ${g.exampleOutput}\n\n### Limitações\n\n${g.limits}\n`;}return s;}
$('download-guide').onclick=()=>current&&download(current.id+'.md',markdown(current));
$('export').onclick=()=>{const header=['ID','Nome','Função','Área','Situação','Responsável','Plataforma','URL','Acesso validado','Documentação','Fonte'];const csv=[header,...records.map(a=>[a.id,a.name,a.role,a.area,a.status,a.owner||'',a.platform||'',a.accessUrl||'',a.accessVerified?'Sim':'Não',a.documentationStatus,a.evidenceSource||'Galeria AI Robots'])].map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');download('inventario-agentes-costal.csv','\ufeff'+csv,'text/csv;charset=utf-8')};
$('gallery-expand').addEventListener('toggle',()=>{if($('gallery-expand').open&&!$('gallery-frame').hasAttribute('src'))$('gallery-frame').src='../'});
load();
